name: Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Use Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Build Rust workspace
        run: cargo build --workspace --release
        working-directory: ./sites/builder-rs

      - name: Build wasm renderer crate
        run: cargo build --target wasm32-unknown-unknown -p renderer-wasm --release
        working-directory: ./sites/builder-rs

      - name: Generate static site
        run: cargo run -p site-builder --release -- --project-dir "$GITHUB_WORKSPACE" --raw-dir "$GITHUB_WORKSPACE/raw" --out-dir "$GITHUB_WORKSPACE/sites/dist/client"
        working-directory: ./sites/builder-rs

      - name: Run Rust tests
        run: cargo test --workspace
        working-directory: ./sites/builder-rs

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: walle45611-github-io
          directory: ./sites/dist/client
