name: Cloudflare Pages

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  submodules: recursive

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Cache NPM dependencies
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-npm-cache
                  restore-keys: |
                      ${{ runner.OS }}-npm-cache

            - name: Install Dependencies
              run: npm i

            - name: Install Pandoc
              run: sudo apt-get update && sudo apt-get install -y pandoc

            - name: Build
              run: npm run build

            # 將 ./public 目錄上傳為名為「site」的 Artifact
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: site
                  path: ./public

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            # 下載名為「site」的 Artifact
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: site
                  path: ./public

            # 部署到 Cloudflare Pages
            - name: Deploy to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: blog
                  directory: ./public
